/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    a: A;
    b: B;
    c: C;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface A {
  id: string;
  name?: string | null;
  amixedblocks?: (string | C)[] | null;
  amixedblocks2?: (string | C)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface C {
  id: string;
  name?: string | null;
  cmixedblocks?:
    | (
        | {
            relationTo: 'a';
            value: string | A;
          }
        | {
            relationTo: 'b';
            value: string | B;
          }
      )[]
    | null;
  cmixedblocks2?: (string | A)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface B {
  id: string;
  name?: string | null;
  bmixedblocks?: (string | null) | C;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
